# Generated by Django 3.2.3 on 2021-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_task_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='title',
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(default='none', max_length=100, verbose_name='Тип предприятия'),
        ),
    ]
