# Generated by Django 3.2.3 on 2021-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='foobar', max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(default='foobar', max_length=100, null=True, verbose_name='Тип предприятия'),
        ),
    ]
