# Generated by Django 3.2.3 on 2021-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210528_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=' ', max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(default=' ', max_length=100, null=True, verbose_name='Тип предприятия'),
        ),
    ]
