# Generated by Django 3.2.3 on 2021-05-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210528_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=' ', null=True, verbose_name='Описание'),
        ),
    ]
